[target.'cfg(all())']
rustflags = [
    "-Wclippy::pedantic",
#    "-Wclippy::unwrap_used", # Advent of code we use this for expediency
    "-Wclippy::expect_used",
    "-Wclippy::doc_markdown",
    "-Wclippy::doc_link_with_quotes",
    "-Wclippy::missing_panics_doc",
    "-Wmissing_docs",
]
